"""initial schema

Revision ID: 202609110001
Revises:
Create Date: 2026-09-11 19:44:27.786393
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "202609110001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_ingestion_runs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("source_name", sa.String(length=64), nullable=False),
        sa.Column("seasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("row_counts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_ingestion_runs")),
    )
    op.create_index(
        op.f("ix_data_ingestion_runs_status"), "data_ingestion_runs", ["status"], unique=False
    )
    op.create_table(
        "model_versions",
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("model_name", sa.String(length=128), nullable=False),
        sa.Column("feature_list", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("train_start_season", sa.Integer(), nullable=False),
        sa.Column("train_start_week", sa.Integer(), nullable=False),
        sa.Column("train_end_season", sa.Integer(), nullable=False),
        sa.Column("train_end_week", sa.Integer(), nullable=False),
        sa.Column("data_artifact_id", sa.String(length=128), nullable=False),
        sa.Column("artifact_uri", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("model_version", name=op.f("pk_model_versions")),
    )
    op.create_table(
        "players",
        sa.Column("player_id", sa.String(length=64), nullable=False),
        sa.Column("player_name", sa.String(length=160), nullable=False),
        sa.Column("position", sa.String(length=16), nullable=False),
        sa.Column("current_team", sa.String(length=8), nullable=True),
        sa.Column("active_status", sa.String(length=32), nullable=True),
        sa.Column("headshot_url", sa.Text(), nullable=True),
        sa.Column("source_name", sa.String(length=64), nullable=False),
        sa.Column("source_retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("player_id", name=op.f("pk_players")),
    )
    op.create_index(op.f("ix_players_current_team"), "players", ["current_team"], unique=False)
    op.create_index(op.f("ix_players_player_name"), "players", ["player_name"], unique=False)
    op.create_index(op.f("ix_players_position"), "players", ["position"], unique=False)
    op.create_table(
        "teams",
        sa.Column("team_code", sa.String(length=8), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("team_code", name=op.f("pk_teams")),
    )
    op.create_table(
        "forecast_generation_runs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("predictions_generated", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["model_version"],
            ["model_versions.model_version"],
            name=op.f("fk_forecast_generation_runs_model_version_model_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecast_generation_runs")),
    )
    op.create_index(
        op.f("ix_forecast_generation_runs_status"),
        "forecast_generation_runs",
        ["status"],
        unique=False,
    )
    op.create_table(
        "games",
        sa.Column("game_id", sa.String(length=64), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("game_type", sa.String(length=16), nullable=True),
        sa.Column("game_date", sa.Date(), nullable=True),
        sa.Column("game_time", sa.Time(), nullable=True),
        sa.Column("game_datetime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("away_team", sa.String(length=8), nullable=False),
        sa.Column("home_team", sa.String(length=8), nullable=False),
        sa.Column("location", sa.String(length=160), nullable=True),
        sa.Column("neutral_site", sa.Boolean(), nullable=True),
        sa.Column("game_status", sa.String(length=32), nullable=True),
        sa.Column("source_name", sa.String(length=64), nullable=False),
        sa.Column("source_retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["away_team"], ["teams.team_code"], name=op.f("fk_games_away_team_teams")
        ),
        sa.ForeignKeyConstraint(
            ["home_team"], ["teams.team_code"], name=op.f("fk_games_home_team_teams")
        ),
        sa.PrimaryKeyConstraint("game_id", name=op.f("pk_games")),
        sa.UniqueConstraint(
            "season", "week", "game_type", "away_team", "home_team", name="game_context"
        ),
    )
    op.create_index(op.f("ix_games_away_team"), "games", ["away_team"], unique=False)
    op.create_index(op.f("ix_games_home_team"), "games", ["home_team"], unique=False)
    op.create_index(op.f("ix_games_season"), "games", ["season"], unique=False)
    op.create_index(op.f("ix_games_week"), "games", ["week"], unique=False)
    op.create_table(
        "player_week_features",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("player_id", sa.String(length=64), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("position", sa.String(length=16), nullable=False),
        sa.Column("games_played_prior", sa.Integer(), nullable=False),
        sa.Column("ppr_points_prev", sa.Float(), nullable=True),
        sa.Column("ppr_points_avg_3", sa.Float(), nullable=True),
        sa.Column("ppr_points_avg_4", sa.Float(), nullable=True),
        sa.Column("ppr_points_avg_8", sa.Float(), nullable=True),
        sa.Column("ppr_points_std_4", sa.Float(), nullable=True),
        sa.Column("targets_prev", sa.Float(), nullable=True),
        sa.Column("targets_avg_3", sa.Float(), nullable=True),
        sa.Column("targets_avg_4", sa.Float(), nullable=True),
        sa.Column("targets_avg_8", sa.Float(), nullable=True),
        sa.Column("receptions_prev", sa.Float(), nullable=True),
        sa.Column("receptions_avg_4", sa.Float(), nullable=True),
        sa.Column("carries_prev", sa.Float(), nullable=True),
        sa.Column("carries_avg_3", sa.Float(), nullable=True),
        sa.Column("carries_avg_4", sa.Float(), nullable=True),
        sa.Column("rushing_yards_prev", sa.Float(), nullable=True),
        sa.Column("rushing_yards_avg_4", sa.Float(), nullable=True),
        sa.Column("receiving_yards_prev", sa.Float(), nullable=True),
        sa.Column("receiving_yards_avg_4", sa.Float(), nullable=True),
        sa.Column("rushing_tds_avg_8", sa.Float(), nullable=True),
        sa.Column("receiving_tds_avg_8", sa.Float(), nullable=True),
        sa.Column("data_artifact_id", sa.String(length=128), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.player_id"],
            name=op.f("fk_player_week_features_player_id_players"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_week_features")),
        sa.UniqueConstraint("player_id", "season", "week", name="player_week"),
    )
    op.create_index(
        op.f("ix_player_week_features_player_id"),
        "player_week_features",
        ["player_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_player_week_features_season"), "player_week_features", ["season"], unique=False
    )
    op.create_index(
        op.f("ix_player_week_features_week"), "player_week_features", ["week"], unique=False
    )
    op.create_table(
        "player_week_predictions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("player_id", sa.String(length=64), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("projection_ppr", sa.Float(), nullable=True),
        sa.Column("baseline_projection_ppr", sa.Float(), nullable=True),
        sa.Column("recent_ppr_average_4", sa.Float(), nullable=True),
        sa.Column("games_played_prior", sa.Integer(), nullable=False),
        sa.Column("history_quality", sa.String(length=16), nullable=False),
        sa.Column("data_as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "history_quality IN ('none', 'limited', 'adequate')",
            name=op.f("ck_player_week_predictions_history_quality"),
        ),
        sa.ForeignKeyConstraint(
            ["model_version"],
            ["model_versions.model_version"],
            name=op.f("fk_player_week_predictions_model_version_model_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.player_id"],
            name=op.f("fk_player_week_predictions_player_id_players"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_week_predictions")),
        sa.UniqueConstraint(
            "player_id", "season", "week", "model_version", name="player_week_model"
        ),
    )
    op.create_index(
        op.f("ix_player_week_predictions_player_id"),
        "player_week_predictions",
        ["player_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_player_week_predictions_season"),
        "player_week_predictions",
        ["season"],
        unique=False,
    )
    op.create_index(
        op.f("ix_player_week_predictions_week"), "player_week_predictions", ["week"], unique=False
    )
    op.create_table(
        "player_game_stats",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("game_type", sa.String(length=16), nullable=False),
        sa.Column("player_id", sa.String(length=64), nullable=False),
        sa.Column("player_name", sa.String(length=160), nullable=False),
        sa.Column("position", sa.String(length=16), nullable=False),
        sa.Column("team", sa.String(length=8), nullable=False),
        sa.Column("opponent_team", sa.String(length=8), nullable=True),
        sa.Column("home_away", sa.String(length=8), nullable=True),
        sa.Column("game_id", sa.String(length=64), nullable=True),
        sa.Column("game_date", sa.Date(), nullable=True),
        sa.Column("passing_yards", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("passing_tds", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("interceptions", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("carries", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("rushing_yards", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("rushing_tds", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("rushing_fumbles_lost", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("targets", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("receptions", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("receiving_yards", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("receiving_tds", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "receiving_fumbles_lost", sa.Float(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("sack_fumbles_lost", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("fumbles_lost_total", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("fantasy_points_ppr", sa.Float(), nullable=False),
        sa.Column("fantasy_points_ppr_source", sa.Float(), nullable=True),
        sa.Column("source_name", sa.String(length=64), nullable=False),
        sa.Column("source_retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("mapping_version", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.game_id"], name=op.f("fk_player_game_stats_game_id_games")
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.player_id"],
            name=op.f("fk_player_game_stats_player_id_players"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_game_stats")),
        sa.UniqueConstraint(
            "player_id", "season", "week", "game_type", name="player_week_game_type"
        ),
    )
    op.create_index(
        op.f("ix_player_game_stats_game_id"), "player_game_stats", ["game_id"], unique=False
    )
    op.create_index(
        op.f("ix_player_game_stats_opponent_team"),
        "player_game_stats",
        ["opponent_team"],
        unique=False,
    )
    op.create_index(
        op.f("ix_player_game_stats_player_id"), "player_game_stats", ["player_id"], unique=False
    )
    op.create_index(
        op.f("ix_player_game_stats_position"), "player_game_stats", ["position"], unique=False
    )
    op.create_index(
        op.f("ix_player_game_stats_season"), "player_game_stats", ["season"], unique=False
    )
    op.create_index(op.f("ix_player_game_stats_team"), "player_game_stats", ["team"], unique=False)
    op.create_index(op.f("ix_player_game_stats_week"), "player_game_stats", ["week"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_player_game_stats_week"), table_name="player_game_stats")
    op.drop_index(op.f("ix_player_game_stats_team"), table_name="player_game_stats")
    op.drop_index(op.f("ix_player_game_stats_season"), table_name="player_game_stats")
    op.drop_index(op.f("ix_player_game_stats_position"), table_name="player_game_stats")
    op.drop_index(op.f("ix_player_game_stats_player_id"), table_name="player_game_stats")
    op.drop_index(op.f("ix_player_game_stats_opponent_team"), table_name="player_game_stats")
    op.drop_index(op.f("ix_player_game_stats_game_id"), table_name="player_game_stats")
    op.drop_table("player_game_stats")
    op.drop_index(op.f("ix_player_week_predictions_week"), table_name="player_week_predictions")
    op.drop_index(op.f("ix_player_week_predictions_season"), table_name="player_week_predictions")
    op.drop_index(
        op.f("ix_player_week_predictions_player_id"), table_name="player_week_predictions"
    )
    op.drop_table("player_week_predictions")
    op.drop_index(op.f("ix_player_week_features_week"), table_name="player_week_features")
    op.drop_index(op.f("ix_player_week_features_season"), table_name="player_week_features")
    op.drop_index(op.f("ix_player_week_features_player_id"), table_name="player_week_features")
    op.drop_table("player_week_features")
    op.drop_index(op.f("ix_games_week"), table_name="games")
    op.drop_index(op.f("ix_games_season"), table_name="games")
    op.drop_index(op.f("ix_games_home_team"), table_name="games")
    op.drop_index(op.f("ix_games_away_team"), table_name="games")
    op.drop_table("games")
    op.drop_index(op.f("ix_forecast_generation_runs_status"), table_name="forecast_generation_runs")
    op.drop_table("forecast_generation_runs")
    op.drop_table("teams")
    op.drop_index(op.f("ix_players_position"), table_name="players")
    op.drop_index(op.f("ix_players_player_name"), table_name="players")
    op.drop_index(op.f("ix_players_current_team"), table_name="players")
    op.drop_table("players")
    op.drop_table("model_versions")
    op.drop_index(op.f("ix_data_ingestion_runs_status"), table_name="data_ingestion_runs")
    op.drop_table("data_ingestion_runs")
    # ### end Alembic commands ###
